language: java
jdk:
  - oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
